### ISSUE TITLE
Update Invoice combination script to also generate a Lenovo Loan only CSV

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/process_csv_report#13]
## Motivation
We need to provide Lenovo with a usage list of how much their loaned nodes are being used

## Completion Criteria
A separate CSV is exported to provide Lenovo GPU usage only.

## Description
- [x] Add new [SU types OpenShift GPUA100SXM4](https://github.com/CCI-MOC/openshift-usage-scripts/issues/48)
- [x] Add new [SU types OpenStack GPUA100SXM4](https://github.com/CCI-MOC/openstack-billing-from-db/issues/47)
- [ ] Split out a new Lenovo_YYYY_MM.csv that includes only the OpenShift GPUA100SXM4 & OpenStack  GPUA100SXM4 SUs
   - [Example](https://docs.google.com/spreadsheets/d/1O7Kqu0cF2nVqNTuNWdzl9NXX6Gg5eB4IZW4LQDItU3w/edit?pli=1#gid=179804284)
   - Include only these columns
      - `Invoice Month`
      - `Project - Allocation`
      - `Institution`
      - `SU Hours (GBhr or SUhr)` - rename to `SU Hours`
      - `SU Type`
   - add 2 new columns
      - `SU Charge` - fill completely with $1.00
         - Worth making this a variable since it will change over time
      - `Charge` - Calculate by multiplying SU Hours by SU Charge
- [ ] Test that Lenovo CSV includes only Lenovo loaned GPU Usage

## Completion dates
Desired - 2024-03-27
Required - 2024-04-18

**Comment by knikolla** [comment]
@joachimweyl Sounds like something for @QuanMPhm? :)

**Comment by joachimweyl** [comment]
@QuanMPhm does this only take into account billable use?
