### ISSUE TITLE
Create Dockerfile to containerize billing script

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#21]
Splitting up #15, and dependent on #20, as the next step before creating a fully automated cronjob to process invoices, we want to create a Docker container containing the bare dependencies needed to run the cloning and billing script.

**Comment by QuanMPhm** [comment]
@knikolla @naved001 As a solution I will create a Docker container with a shell script which does the following:
- Clone the non-billable repo
- Fetches the invoices for the previous month from S3 storage
- Passes all relevant files to `process_report.py`

**Comment by knikolla** [comment]
> @knikolla @naved001 As a solution I will create a Docker container with a shell script which does the following:
> 
> * Clone the non-billable repo
> * Fetches the invoices for the previous month from S3 storage
> * Passes all relevant files to `process_report.py`

@QuanMPhm And 4th step, uploads the generated invoices in the appropriately named way.

**Comment by QuanMPhm** [comment]
My questions/things I need so far are:
- I need access to a list of Old PIs. Where is that currently stored? @naved001 suggested that it should be placed in the nonbillable repo alongside other files that would impact billing.
- @joachimweyl @knikolla  Since we want this Docker container to upload the processed invoices back to S3, what should be the naming convention for all the HU-only, HU & BU only, Lenovo-only, and the PI-specific invoices?

**Comment by QuanMPhm** [comment]
@joachimweyl If it's not a big problem, I'll have the file names be as follows:
```
HU&BU - NERC Total Invoice <YYYY>-<MM>.csv
BU Internal - NERC BU <YYYY>-<MM>.csv
Lenovo-only - Lenovo <YYYY>-<MM>.csv
PI specific - PI Invoices/<University>_<PI>_<YYYY>-<MM>.csv
```

It would juts simplify the code if the invoice month (YYYY-MM) is consistently placed at the end of the filename.

**Comment by joachimweyl** [comment]
Please make sure HU&BU is labeled `NERC-<YYYY>-<MM>-Total-Invoice.csv` as that is the file name MGHPCC requested. The others look fine.
