### ISSUE TITLE
Package the invoice processing container into a Openshift Cronjob

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#22]
Dependant on #21, the goal is to create a Cronjob that runs at the beginning of each month which performs the following tasks in order:
- Fetch monthly usage CSVs from S3
- Fetch nonbillable data from the CCI-MOC private repo
- Fetch the list of old PIs from S3 (maybe this file should be relocated to our nonbillable Github repo?)
- Process the invoices
- Upload the processed to S3

I have  a question regarding the precise details, and I'll likely add more as I progress through this issue:
- @joachimweyl Currently the invoice processing script exports not only the combined Billable and Non-Billable invoices, but also the HU-only, HU & BU only, Lenovo-only, and the PI-specific invoices as well. Should we decide on a naming convention for these files and how they should be stored in S3?

**Comment by joachimweyl** [comment]
@knikolla & @naved001 what do you think about this folder structure?

- Billable
   - Complete
   - BU&HU
   - Lenovo
   - PI
- Non-Billable
   - Complete

@QuanMPhm Harvard no longer requires their own CSV. We no longer need to create it, that is why the Billable folder does not contain an HU folder.
