### ISSUE TITLE
Fetch and update old pi file to s3

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/process_csv_report#27]
Required by #21 and #22 

- Need to generate an initial old pi file containing pi names and month.
- Upload this initial pi file to B2 in a known location manually.
- Update the code to fetch the old pi file.
- Update the code to write a new pi file with the new pis encountered this month.
- Upload the old (new) pi file to s3.

**Comment by QuanMPhm** [comment]
@knikolla @joachimweyl Would a location like `Invoices/old-pi.csv` be a good place for the file?

**Comment by joachimweyl** [comment]
[here](https://docs.google.com/spreadsheets/d/1yMB1px5crz3KCw2tk-rZItxgzS85rHO0YPoSXpMgW0c/edit?pli=1#gid=96108463&range=A:A) is a list of the PIs.

**Comment by QuanMPhm** [comment]
May I upload this to the nerc_invoicing bucket?

**Comment by knikolla** [comment]
> Permission to upload this to the nerc_invoicing bucket?

Yes, in the above mentioned location after you have translated it into a csv file that the `process_csv_report` can understand.

**Comment by QuanMPhm** [comment]
@joachimweyl @knikolla Should I write that the first month these PIs appeared in our invoices was 2024-03? This will only matter when we decide to process past invoices.

**Comment by joachimweyl** [comment]
are you tracking when they were added?

**Comment by joachimweyl** [comment]
In that case, use [this](https://docs.google.com/spreadsheets/d/1yMB1px5crz3KCw2tk-rZItxgzS85rHO0YPoSXpMgW0c/edit?pli=1#gid=0) list as it says what month they were added. Anybody not on this list but on the first list can be considered added on July.
