### ISSUE TITLE
Standardize on precision of numbers for invoicing

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/process_csv_report#35]
Capture a decision on the amount of precision (digits after the decimal point) we want for the below values

- Rate
- Cost
- Balance

**Comment by joachimweyl** [comment]
Rate - 3 decimal places
Cost - 2 decimal places
Balance - 2 decimal places

**Comment by naved001** [comment]
I have been rounding the cost to 2 decimal places.

https://github.com/CCI-MOC/openshift-usage-scripts/blob/be997dc7f2332a6b04e08c03f595abba1912710b/openshift_metrics/utils.py#L368


Specifically, I have been using ROUND_HALF_UP because that's what I learnt in maths in school.

**Comment by knikolla** [comment]
@joachimweyl For storage, the CSV processes per GB rather per TB, 3 decimal points for the rate aren't enough for that. I can [fix the presentation](https://github.com/nerc-project/coldfront-plugin-cloud/issues/157).

**Comment by joachimweyl** [comment]
sorry you are completely correct let me fix my comment.

**Comment by joachimweyl** [comment]
@naved001 what is ROUND_HALF_UP is that round-up or does it only round up if it is above .5?

**Comment by naved001** [comment]
As per the python docs: https://docs.python.org/3/library/decimal.html#decimal.ROUND_HALF_UP

The effect is that, it rounds up if it equal to or above 5, otherwise it rounds it down.
e. g. `4.325` will be rounded to `4.33`. 

The default rounding method rounds to the nearest integer. 

default method:
```
>>> Decimal('4.325').quantize(Decimal(".01"))
Decimal('4.32')
>>> Decimal('4.315').quantize(Decimal(".01"))
Decimal('4.32')
```

ROUND_HALF_UP:
```
>>> Decimal('4.325').quantize(Decimal(".01"), rounding="ROUND_HALF_UP")
Decimal('4.33')
>>> Decimal('4.315').quantize(Decimal(".01"), rounding="ROUND_HALF_UP")
Decimal('4.32')
```
