### ISSUE TITLE
Create a timestamped backup of PI.csv when the invoice processing script is ran

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#41]
Similar to how the processed invoices are timestamped and uploaded to a backup folder in S3, we want `PI.csv` to also be backed up

**Comment by QuanMPhm** [comment]
@knikolla @joachimweyl  This functionally should be equivalent, but should I make the backup of the PI file **before** or **after** it has been modified?

**Comment by knikolla** [comment]
> Before. Just incase something goes wrong with the previous run you know that a backup is made first thing.

++. Backing up data before you change it ensures you have a copy of the data which you can roll back to in case something goes wrong during processing.
