### ISSUE TITLE
Investigate the Invoivce feature of Coldfront's UI

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#51]
Through @knikolla's suggestion, the Coldfront UI has an "Invoice" button, and one of our current problems is how to give MOCA users access to their invoices/current usage costs. It may be worth the time to see what features Coldfront may have regarding invoicing.

**Comment by QuanMPhm** [comment]
@knikolla @joachimweyl After looking at the Coldfront UI for a while, it seems the "Invoice" button that @knikolla pointed out leads to an invoice page, which lists allocations with a status that belongs in this list: `['Paid', 'Payment Pending', 'Payment Requested', 'Payment Declined', ]`

This is based on:
https://github.com/ubccr/coldfront/blob/eaf90d26f4c6f76addc5ac62de202b6be9196d6a/coldfront/core/allocation/models.py#L83-L87

Coldfront does not seem to have special treatment for allocations with these statuses. Nothing in the code seems to set an allocation's attribute, so it is a purely user-determined field.

Doing a bit more reading, I noticed that Coldfront does contain some logic for displaying an allocation's usage of its quotas. More specifically, if an allocation has attributes that are usage limits/quotas  (Limits on CPU hours, RAM, memory, etc), Coldfront's UI will display how much of that quota is used in the form of a semi-pie chart, as shown below:
![Screenshot from 2024-05-14 14-57-38](https://github.com/CCI-MOC/process_csv_report/assets/74226479/1efb5c75-df58-451c-96f1-94158039efa1)

From what I could find, there does not seem to be any way in the Coldfront UI (besides the admin console) to change the usage of a given quota. The only code I see that directly changes the usage values are through some [XDMod integration code](https://github.com/ubccr/coldfront/blob/eaf90d26f4c6f76addc5ac62de202b6be9196d6a/coldfront/plugins/xdmod/management/commands/xdmod_usage.py#L143)?

I understand our main concern is to display how much costs the PI has incurred for a given allocation over a period of time, and that for some of our quotas (CPU quota, RAM quota, etc), it doesn't make sense to display how much of that quota has been used, or to even assign a 'usage' value to it. Therefore, I think that's not much in Coldfront's code that we can make use of for displaying billing/usage. I don't think there is much to present for the demo?

**Comment by knikolla** [comment]
Marking this as closed. It seems it doesn't really have much in terms of invoicing features besides tracking status and usage of attributes.
