### ISSUE TITLE
Break up `process_report.py` into smaller, modular files

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#52]
`process_report.py` has reached a point where it contains code to handle a variety of unrelated tasks. After all the PRs up until #50 is merged, I believe the Python program should be broken up into the following files:
- `io.py`, containing functions to export and import the various files needed for invoice processing, from both local and S3 storage
- `processing.py`, containing functions which will process the input invoices
- `main.py`, which will call functions from `io.py` and `processing.py`
- `util.py`, containing utility functions, which may be used by all of the three files above

@knikolla @naved001 Would you have other suggestions on how I would break up `process_report.py`?

**Comment by knikolla** [comment]
We can do better than just breaking it up into different files. There’s significant refactoring that can be applied to make the code more easy to follow and scalable. I’ll write down some ideas in the coming days.

**Comment by knikolla** [comment]
@QuanMPhm @naved001  I spent some time sketching out how I'd like to see this refactored. 

- Create an `Invoice` class which implements some basic functionality that all invoices do, like how to write to file and where to upload to s3.
- Find the common steps of processing that most invoices go through, with some quick looking I think the steps can be divided into `prepare`, `process`, `prepare_export`. 
- Subclass invoice for each of the Invoices that we need and overload the above 3 methods. Each of the invoices can be implemented in a separate file `process_report/invoices/<invoice_name>.py`
- For everything that depends on a previous invoice, you can access the `data` attribute of the processed invoice.

For example

```python
@dataclass
class Invoice:
    name: str
    invoice_month: str
    data: DataFrame

    def process(self):
        self._prepare()
        self._process()
        self._prepare_export()

    @property
    def output_path(self) -> str:
        return f"{self.name} {self.invoice_month}.csv"

    @property
    def output_s3_key(self) -> str:
        return f"Invoices/{self.invoice_month}/{self.name} {self.invoice_month}.csv"

    @property
    def output_s3_archive_key(self):
        return f"Invoices/{self.invoice_month}/Archive/{self.name} {self.invoice_month} get_iso8601_time().csv"

    def _prepare(self):
        """Prepares the data for processing.

        Implement in subclass if necessary. May add or remove columns
        necessary for processing, add or remove rows, validate the data, or
        perform simple substitutions.
        """
        pass

    def _process(self):
        """Processes the data.

        Implement in subclass if necessary. Performs necessary calculations
        on the data, e.g. applying subsidies or credits.
        """
        pass

    def _prepare_export(self):
        """Prepares the data for export.

        Implement in subclass if necessary. May add or remove columns or rows
        that should or should not be exported after processing."""
        pass

    def export(self):
        self.data.to_csv(self.output_path)
        # and upload to s3 based on key properties
        # whatever wants a different path you can overload the property in the subclass
```

and 

```python
@dataclass
class BillableInvoice(invoice.Invoice):
    """"""
    nonbillable_pis = list[str]
    nonbillable_projects = list[str]

    name = "NERC Billable"

    def _prepare_export(self):
        self.data = self.data[
            ~self.data[invoice.PI_FIELD].isin(self.nonbillable_pis)
            & ~self.data[invoice.PROJECT_FIELD].isin(self.nonbillable_projects)
        ]
```

```python
PROJECT_FIELD = "Project"
SUBSIDY_FIELD = "Subsidy"


@dataclass
class BUInvoice(invoice.Invoice):
    name: str = "BU"

    subsidy_amount: Decimal = Decimal("100")

    def _prepare(self):
        def get_project(row):
            project_alloc = row[base.PROJECT_FIELD]
            if project_alloc.rfind("-") == -1:
                return project_alloc
            else:
                return project_alloc[: project_alloc.rfind("-")]

        self.data = self.data[self.data[base.INSTITUTION_FIELD] == "Boston University"]
        self.data[PROJECT_FIELD] = self.data.apply(get_project, axis=1)
        self.data[SUBSIDY_FIELD] = Decimal("0")

    def _process(self):
        pi_list = self.data[invoice.PI_FIELD].unique()

        for pi in pi_list:
            pi_projects = self.data[self.data[invoice.PI_FIELD] == pi]
            remaining_subsidy = self.subsidy_amount

            for i, row in pi_projects.iterrows():
                project_remaining_cost = row[invoice.BALANCE_FIELD]
                applied_subsidy = min(project_remaining_cost, remaining_subsidy)

                dataframe.at[i, invoice.SUBSIDY_FIELD] = applied_subsidy
                dataframe.at[i, invoice.BALANCE_FIELD] = row[invoice.BALANCE_FIELD] - applied_subsidy
                remaining_subsidy -= applied_subsidy

                if remaining_subsidy == 0:
                    break

    def _prepare_export(self):
        self.data = self.data[
            [
                invoice.INVOICE_DATE_FIELD,
                invoice.PI_FIELD,
                PROJECT_FIELD,
                invoice.COST_FIELD,
                invoice.CREDIT_FIELD,
                SUBSIDY_FIELD,
                invoice.BALANCE_FIELD,
            ]
        ]
```

**Comment by joachimweyl** [comment]
@QuanMPhm do you expect to have all the parts of this finished by the end of this sprint? If not I suggest breaking this into multiple issues and associating them directly with the PR's you already have and whatever new PR's might be needed to close this out.

**Comment by QuanMPhm** [comment]
@joachimweyl I expect the review process for every PR related this issue to take at least another week. I'll close this issue now and break it up into smaller issues then.

**Comment by joachimweyl** [comment]
In the future you can use the initial "parent" issue as the first issue in the group of "children" to save time and retain comments.
