### ISSUE TITLE
Output 0.000009 instead of 9.00E-06

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/process_csv_report#56]
Continuation of https://github.com/nerc-project/coldfront-plugin-cloud/issues/157

The representation issue might be because that column is read as a float. (No operation are performed with it so that's not really a problem)

```
>>> a = "0.000009"
>>> float(a)
9e-06
>>> Decimal(a)
Decimal('0.000009')
```

**Comment by knikolla** [comment]
Perhaps we can just declare that column a string data type? That would avoid any changes to it.

**Comment by joachimweyl** [comment]
@QuanMPhm it looks like the most recent output was in this format, did you already sneak this in?

**Comment by knikolla** [comment]
@joachimweyl in the processed invoices it does still appear as `9.00E-06`. ex. filtered_output.csv

**Comment by joachimweyl** [comment]
Oh, interesting I used Ctrl Shift V to paste and apparently since I was using my previous template it formatted it correctly. Ignore my earlier comment.
