### ISSUE TITLE
Add post invoice script automation script to break Invoice into groups by PI

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/process_csv_report#7]
## Motivation
Regularly let users know how many resources they have used prior to receiving their official invoice.

## Completion Criteria
Invoice CSV grouped into groups by PI

## Description
- [ ] Create a way to group data in the invoice CSV by PI (individual CSVs or a database whatever is easier, developer's prerogative)
- [ ] This will then be used to email out this information but that is a different issue

## Completion dates
Desired - 2024-02-14
Required - TBD

**Comment by naved001** [comment]
>  Create a way to group data in the invoice CSV by PI

Do we want separate CSVs for each PI? Because I don't know how we can "group" things in a csv

**Comment by joachimweyl** [comment]
They can be their own CSV or they can be a database, whatever we want to get in a format we can add to an email.

**Comment by QuanMPhm** [comment]
@naved001  @joachimweyl My proposed solution will be to make an addition to the `process_report.py` to divide the combined invoice CSV into smaller CSVs, grouped by PI. These smaller PI-specific invoice CSVs will be exported into a folder provided by the user (defaults to current directory), and the name format for each PI CSV will be:
`<Instituition_name>_<PI email>_<invoice month>`

Feel free to provide any further suggestions.

**Comment by joachimweyl** [comment]
can you explain "folder provided by the user" further?
also let's make sure the csv we are dividing is the billable csv not the non-billable csv.
