### ISSUE TITLE
Create a flowchart/diagram of how the data is processed in this repo

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/process_csv_report#74]
It has become difficult to track on how we are manipulating data and what steps are dependent on each other (if any)

**Comment by joachimweyl** [comment]
@msdisme do we have a standard flowchart software we use? Is Draw.io the opensource flowchart of choice?
@QuanMPhm can you take a first stab at this and I will review and make suggestions once you create the first draft?

**Comment by QuanMPhm** [comment]
@naved001 @joachimweyl Is this fine?
![Untitled Diagram drawio](https://github.com/user-attachments/assets/859f29ba-d6e9-44eb-856e-cc975aea7544)

**Comment by joachimweyl** [comment]
looks right to me.

**Comment by naved001** [comment]
@QuanMPhm thanks Quan, this looks good to me. My github is in dark mode so I didn't see the arrows at first and was really confused until I clicked on the image which showed me the whole thing.

This diagram (maybe with some details) should be in the readme of this repository and then we can close this issue.
