### ISSUE TITLE
Index present in Lenovo csv invoice

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/process_csv_report#78]
File was exported without `index=False`, probably needs to be changed in the Invoice base class.

https://github.com/CCI-MOC/process_csv_report/blob/287afea5875b32bf25b8727b2790c54f14137328/process_report/invoices/invoice.py#L74

**Comment by joachimweyl** [comment]
@QuanMPhm do you need more issues, or is your plate full?

**Comment by QuanMPhm** [comment]
@joachimweyl This is a one line fix. I can take this
