### ISSUE TITLE
Add new CSVs for prepaid group billing

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/process_csv_report#80]
As part of implementing prepaid group billing, several CSVs containing information needed for prepaid group billing needs to be stored in a private Github repo, as well as in several backup locations. These CSVs include:
- Prepaid Group Debit Ledger: Containing all debits for each prepaid group every month
- Prepaid Group Credit Ledger: Containing all credits for each group every month
- Prepaid Group Contacts: Has group name, contact email, and whether they are MGHPCC managed
- Prepaid Group Projects: Containing information on the projects in each prepaid group

We need to decide where these files will be stored. @knikolla @naved001 @joachimweyl I will wait for your thoughts before continuing.

**Comment by joachimweyl** [comment]
What do people think of
1. CCI-MOC/prepaid-group-billing
1. CCI-MOC/prepaid-group-tables
1. CCI-MOC/prepaid-billing
1. CCI-MOC/prepaid-tables
1. Rename non-billable-projects to private-billing-tables and share all our private tables in that repo

**Comment by knikolla** [comment]
@joachimweyl I'd go with 5, I don't see why this needs to be a separate repo. So renaming nonbillable to something more generic is the best solution.

**Comment by joachimweyl** [comment]
@naved001 to cover all our bases, is any code using CCI-MOC/non-billable-projects hardcoded that will need to be changed?

**Comment by knikolla** [comment]
> @naved001 to cover all our bases, is any code using CCI-MOC/non-billable-projects hardcoded that will need to be changed?

@joachimweyl GitHub maintains redirects after a repo is renamed, so nothing will break. 

From [renaming a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)
> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.

**Comment by QuanMPhm** [comment]
@knikolla @naved001 Should I write a separate issue to decide the backup locations for these files?

**Comment by QuanMPhm** [comment]
@knikolla @naved001 @joachimweyl Do you have any input on the above question, since we're currently making progress on refactoring?
