### ISSUE TITLE
Add URI to MGHPCC Invoice

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/process_csv_report#83]
## Motivation
URI (University of Rhod Island) has signed their MOU and we can now add them to the MGHPCC Invoice.

## Completion Criteria
Update the script to no longer generate the HU_BU.csv it should now create NERC-YYYY-MM-Total-Invoice.csv and it will include BU, HU & URI.

## Description
- [ ] Update script to no longer create HU_BU.csv
- [ ] Update script to generate a CSV called NERC-YYYY-MM-Total-Invoice.csv
- [ ] Filter into it BU & HU much like HU_BU.csv but now add URI
   - make sure this is done in a way that as we add more MOUs it will be a quick process to add new Institutions to this list
   - if possible maybe there is a way to track when new Institutions are added via [nerc-rates](https://github.com/CCI-MOC/nerc-rates)?
- [ ] Update flowchart for renamed invoice

## Completion dates
Desired - 2024-08-29
Required - TBD

**Comment by joachimweyl** [comment]
@QuanMPhm do you have space on your plate for this issue? It might not be a 3 story point issue that was just my initial guess, feel free to update the estimate. There is no rush on this, I can do it manually the first month if I have to.

**Comment by QuanMPhm** [comment]
@joachimweyl This should be a fairly quick change. I will do it by the end of this month.

**Comment by QuanMPhm** [comment]
@joachimweyl @knikolla For a easy method of adding more institutions into the NERC Total Invoice, I believe making a file like `included_institutions.txt` listing the included institutions would be simplest. We can put it in this repo or somewhere else?

**Comment by knikolla** [comment]
@QuanMPhm Let me think about this a bit more.

**Comment by QuanMPhm** [comment]
@knikolla Do you have any thoughts on this yet?

**Comment by knikolla** [comment]
@QuanMPhm I think it's fine to hardcode the list of institutions in the invoice class for now as I don't want to create more single purpose files for the moment. Especially ones that are really slow to change, like this. 

One we have enough new requirements for metadata related to institutions we can extend `institute_map.json` to contain it.
